### ISSUE TITLE
baru `0.1.1` not usable?

### ISSUE THREAD

**Issue by da-kami** [comit-network/baru#35]
Could not integrate baru into the extension wallet - I get build errors. 
Details:

https://github.com/comit-network/waves/pull/199

**Comment by luckysori** [comment]
Thanks for the report and sorry about that. I'll take a look.

**Comment by luckysori** [comment]
My understanding of the problem is that `baru` was depending on two different versions of `rust-elements`:

- 0.17 as explicitly mentioned in the `Cargo.toml`.
- 0.18 via `elements-miniscript`.

In `baru` and in CI, the `Cargo.lock` file was such that there were no compilation issues. But because this is a library crate, we don't check the lockfile into version control, so the situation was different in `waves`.

Does that make some sense? cc @thomaseizinger.

In any case, we will release a 0.2.0 version of `baru` with fixed and compatible versions for all the dependencies and you can ignore 0.1.1. The upgrade to `rust-elements:0.18.0` will break things in `waves` (I've tested it locally) which is why we'll be releasing version 0.2.0. I can help you with the upgrade, since I've already done it locally.

**Comment by da-kami** [comment]
You could remove `0.1.1` release if you find the time, we will ignore it :)

**Comment by thomaseizinger** [comment]
> Does that make some sense? cc @thomaseizinger.

It is a weird problem indeed! Can't fully pin down what is wrong but yeah, releasing 0.2 sounds good to me. If 0.1.1 were released, I would probably yank it so removing the release entirely sounds like a good idea.
