### ISSUE TITLE
Loan term should be a timestamp

### ISSUE THREAD

**Issue by bonomat** [comit-network/baru#41]
At the moment the timelock in our loan is modeled in block heihgt but this could be an issue: 

Let's assume our timelock is 30 days. 
On Liquid this _should_ be 30 (days) * 24 (hours) * 60 (blocks per hour) blocks (43200). 
As long as Liquid behaves exactly this way, our loan will be 30 days. 

While at the moment blocks are ridiculously accurate on the second, this might not always be the case.
This means, the loan can randomly be longer or even shorter if the blocks/minute change. 

Let's assume there was a burst of 1000 blocks. Suddenly your loan term is shorted by almost a day. 

Imho the simplest solution for preventing this upfront is by using a timestamp instead of blocks. 

Good thing is, OP_CLTV supports timestamps [0] : OP_CLTV interprets the locktime as timestamp if the value is `>= 500000000`

This would also simplify the client side/UI as we don't have to do conversations back and from blocks to date.

[0] https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki
[1] https://github.com/bitcoin/bitcoin/blob/b620b2d58a55a88ad21da70cb2000863ef17b651/src/script/script.h#L37-L39

**Comment by bonomat** [comment]
Might be important for #https://github.com/comit-network/baru/pull/39

**Comment by luckysori** [comment]
From an API standpoint, do we need to change anything? One can already pass in a timelock `>= 500000000` which will be interpreted as a timestamp.

**Comment by bonomat** [comment]
True that. Only thing that should change is the doc then :)

**Comment by luckysori** [comment]
As in specify that the timelock represents a timestamp? I would hesitate to do that because I think the protocol works fine with block height. It's just that your application only wants to use timestamps.

We could model the timelock as an `enum` so that you can explicitly choose the kind of timelock you want to use. That would be nice actually. Then users of the library don't need to understand the inner workings of `OP_CLTV` to use the library.
